version: "3"
services:
  app:
    image: "nest-backend"
    ports:
      - "3007:3007"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    volumes:
      - ./playground:/usr/src/app/playground:rw
      - ./prisma:/usr/src/app/prisma

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: "nest-frontend"
    ports:
      - "4200:4200"

volumes:
  db-data:
